# Generated by Django 4.2.1 on 2023-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('tage', models.IntegerField()),
                ('tsubject', models.CharField(max_length=100)),
            ],
        ),
    ]
